#!/bin/bash
#
# spark: Start/Stop Spark daemons.
#
# chkconfig: - 85 15
# description: Start or stop the Spark daemons.

# Source function library.
. /etc/rc.d/init.d/functions

# Get function from functions library
start() {
    # Start Spark daemons
    su - spark -c "/usr/local/spark/sbin/start-all.sh"
    # Start Job History Server
    su - spark -c "/usr/local/spark/sbin/start-history-server.sh"
}

stop() {
    # Start Spark daemons
    su - spark -c "/usr/local/spark/sbin/stop-all.sh"
    # Start Job History Server
    su - spark -c "/usr/local/spark/sbin/stop-history-server.sh"
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0